"""
Data writer for Jekyll YAML data files.
Writes structured data to _data/ directory.
"""

import os
from typing import Dict, Any
import yaml

from scripts.config import logger


class DataWriter:
    """
    Writes YAML data files for Jekyll.
    
    Handles:
    - Type-locale filename pattern (profile-en.yml, header-es.yml)
    - YAML serialization with comments
    - UTF-8 encoding
    """
    
    def __init__(self, base_path: str = '.') -> None:
        """
        Initialize data writer.
        
        Args:
            base_path: Base directory path (default: current directory)
        """
        self.base_path = base_path
        self.data_dir = os.path.join(base_path, '_data')
    
    def _ensure_data_folder(self) -> str:
        """
        Ensure _data/ folder exists.
        
        Returns:
            Path to _data folder
        """
        if not os.path.exists(self.data_dir):
            os.makedirs(self.data_dir, exist_ok=True)
            logger.info(
                f"📁 FOLDER_CREATED "
                f"path={self.data_dir}"
            )
        
        return self.data_dir
    
    def _generate_header_comment(
        self,
        content_type: str,
        locale: str
    ) -> str:
        """
        Generate YAML file header comment.
        
        Args:
            content_type: Content type name
            locale: Locale code
        
        Returns:
            Header comment string
        """
        return (
            f"# {content_type} data for {locale} locale\n"
            f"# Generated by scripts/transformers/\n"
            f"# DO NOT EDIT MANUALLY - Changes will be overwritten\n"
            f"\n"
        )
    
    def write_data_file(
        self,
        data: Dict[str, Any],
        content_type: str,
        locale: str
    ) -> None:
        """
        Write data to YAML file.
        
        Args:
            data: Data dictionary to serialize
            content_type: Content type (e.g., 'profile', 'header', 'footer')
            locale: Locale code
        
        Raises:
            IOError: If file write fails
        """
        # Ensure _data folder exists
        self._ensure_data_folder()
        
        # Generate filename: {content_type}-{locale}.yml
        filename = f"{content_type}-{locale}.yml"
        file_path = os.path.join(self.data_dir, filename)
        
        try:
            # Serialize to YAML
            yaml_content = yaml.dump(
                data,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
                indent=2
            )
            
            # Add header comment
            header = self._generate_header_comment(content_type, locale)
            full_content = header + yaml_content
            
            # Write to file
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(full_content)
            
            logger.info(
                f"✅ DATA_WRITTEN "
                f"path={file_path} "
                f"content_type={content_type} "
                f"locale={locale}"
            )
            
        except Exception as e:
            logger.error(
                f"❌ WRITE_FAILED "
                f"path={file_path} "
                f"error={str(e)}"
            )
            raise IOError(f"Failed to write data file: {str(e)}")
    
    def write_multiple_data_files(
        self,
        data_items: list[tuple[Dict[str, Any], str, str]]
    ) -> None:
        """
        Write multiple data files.
        
        Args:
            data_items: List of tuples (data, content_type, locale)
        """
        success_count = 0
        failed_count = 0
        
        for data, content_type, locale in data_items:
            try:
                self.write_data_file(data, content_type, locale)
                success_count += 1
            except Exception as e:
                logger.error(
                    f"❌ DATA_WRITE_FAILED "
                    f"content_type={content_type} "
                    f"locale={locale} "
                    f"error={str(e)}"
                )
                failed_count += 1
        
        logger.info(
            f"📊 DATA_FILES_WRITTEN "
            f"success={success_count} "
            f"failed={failed_count}"
        )
